### ISSUE TITLE
Private Instance | Ec2 Agent Scaling

### ISSUE THREAD

**Issue by pkamran** [catchpoint/WebPageTest#1212]

**Comment by pkamran** [comment]
We are using Private WPT instance for our Client and Recently we have made changes in Settings.ini where we increased the below value to 20. Most the time We can see the 20 Agents are up and running in AWS console but WPT Master is not assigning work to all the agents it is only sending work to 1 agent and even getTesters.php is showing one active agent.  ec2-instances.dat file in tmp folder also give count as 20 agent for the ami. 
Any help will be really helpful.
 EC2.us-east-1-linux.max=20

**Comment by ankitjain082** [comment]
Hi @pkamran,

I am facing same issue for Auto scaling on AWS, Please let me know if you have any solution for the same.

Thanks,
Ankit Jain
