### ISSUE TITLE
Some javascripts are not loaded in our private instance. 

### ISSUE THREAD

**Issue by abhagupta** [catchpoint/WebPageTest#1216]
We are investigating an issue in which some javascripts are not loaded in our private instance (desktop) but are loaded in public instance. For example,

 skeleton.js in https://www.webpagetest.org/result/181102_88_2a6477ca058f625d297a18de246944cb/1/details/

and 
moatad.js

https://www.webpagetest.org/result/181102_V2_ef2d1cf6d4c5f6560ba2b6844d546fb5/1/details/

FYI, these js files are loaded after document complete.    

Could you shed some light on why this would happen?

**Comment by Lily9991** [comment]
here's the test result on private instance:

moatad.js: http://wptserver6951.cloudapp.net/details.php?test=181101_XM_1WE
skeleton.js: http://wptserver6951.cloudapp.net/details.php?test=181101_N3_1WB
