### ISSUE TITLE
Private-instance getTesters.php is blank/has no content

### ISSUE THREAD

**Issue by stephendonner** [catchpoint/WebPageTest#1237]
Neither https://[private instance hostname]/getTesters.php nor https://[private instance hostname]/getTesters.php?f=html show us any content/data.

We should see the six EC2 wptagent instances, etc., but we just get a 200 OK returned, instead.

I don't know if it's helpful (and I know server/agent logs would be helpful, so we'll work on those), but here's a HAR file from a sample broken session: https://drive.google.com/file/d/1KsuHF2VW1bhMghoGl9do0Clcj62OsFdo/view?usp=sharing

/cc @jbuck @davehunt 

<img width="1920" alt="screen shot 2019-01-08 at 5 00 16 pm" src="https://user-images.githubusercontent.com/387249/50869117-9098c100-1367-11e9-9898-47b6079c06bd.png">

**Comment by pmeenan** [comment]
Try adding a debug=1 query param. That should get it to log or display any php errors that might be breaking the page.

**Comment by stephendonner** [comment]
Hmm, that didn't seem to do anything, but it did acknowledge it as a query param in the XML/XSL response(s).

I or @jbuck can hopefully find something in the logs tomorrow.

<img width="2032" alt="screen shot 2019-01-09 at 10 01 33 pm" src="https://user-images.githubusercontent.com/387249/50949249-4fcda480-145a-11e9-86bc-ee8e6f89f7c6.png">
