### ISSUE TITLE
Last Painted Hero (LPH) metric is overly sensitive to browser artifacts

### ISSUE THREAD

**Issue by theball** [catchpoint/WebPageTest#1274]
See the "Waiting for..." text at the bottom of [this image](https://www.webpagetest.org/results/19/05/30/B7/081b99368f77706a1c3b771aad1d1b8a/video_3_3/ms_000100.jpg), which comes from the browser, not the web page.

![image](https://user-images.githubusercontent.com/64680/58752987-ea13a080-846c-11e9-937b-0a4065483976.png)

Those updates increase the LPH number. See the full filmstrip [here](https://www.webpagetest.org/video/compare.php?tests=190530_B7_081b99368f77706a1c3b771aad1d1b8a-r%3A3-c%3A0-s%3A3&thumbSize=200&ival=100&end=visual). Perhaps a simple fix is to ignore the bottommost pixels of the viewport.

I'm excited about LPH. It seems like the metric that most closely aligns to user perceived page load. Speed Index is good but IMO gives too much credit to the pattern of showing shimmers/skeletons so I'd love to see some of these kinks with LPH resolved. 

/cc @paulirish

**Comment by josephwynn-sc** [comment]
Hey, thanks for reporting this! I think WPT already has some mechanism to ignore the status bar, so it should be trivial to implement the same thing for hero times. Failing that, a quick-but-naïve fix would be to ignore the bottom pixels of each frame.

I don't have time to do this at the moment but if somebody wants to have a crack at that, the code is [in visualmetrics.py](https://github.com/WPO-Foundation/wptagent/blob/6ab2492/internal/support/visualmetrics.py#L1507).
