### ISSUE TITLE
TTI on safari

### ISSUE THREAD

**Issue by soulcorrosion** [catchpoint/WebPageTest#1287]
Hi @pmeenan, doesn't safari report long tasks? The TTI I get using any iPhone is always super fast without any reds on main thread activity.

**Comment by pmeenan** [comment]
TTI is calculated using the main thread data from dev tools. It looks like collection of the main-thread activity in Safari isn't working very well and stops early in the document: https://www.webpagetest.org/result/190719_XY_2d18bf0336c5f91ae4a2dc2de1812c83/

If/when the timeline capture support improves for Safari the TTI will also become accurate.

And no, for reference, the actual long tasks API is currently Chromium-only: https://developer.mozilla.org/en-US/docs/Web/API/Long_Tasks_API
