### ISSUE TITLE
setUserAgent not respected in scripted tests

### ISSUE THREAD

**Issue by gilbertococchi** [catchpoint/WebPageTest#1304]
https://webpagetest.org/result/191011_GX_0c8cb1c62558a1889e0f9bbc5136ffc8/1/details/#step1_request198

Script:
```
setActivityTimeout	30000
setUserAgent	Mozilla/5.0 (Linux; Android 8.1.0; Pixel 2 Build/OPM1.171019.011) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.146 Mobile Safari/537.36 PTST/191007.161036
navigate	https://mobile.yoox.com/us/women/clothing%20new%20arrivals/shoponline
sleep	30
execAndWait	 document.querySelectorAll('a.itemContainer')[0].click()
```

Request Headers User Agent for https://mobile.yoox.com/scripts/client/yoox/js/dist/sw.js
`user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36
`

Expected User Agent: 
`
user-agent: Mozilla/5.0 (Linux; Android 8.1.0; Pixel 2 Build/OPM1.171019.011) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.146 Mobile Safari/537.36 PTST/191007.161036
`
Also when adding the standard Chrome Mobile UA Emulation and/or the Discard HTTP Headers option the request would still receive the Default Chrome UA:

https://webpagetest.org/result/191011_N1_706c425c6e3488579c142d171514f112/1/details/#step1_request186

https://webpagetest.org/result/191011_C5_da68801f738d0ea907bef80f155be3bd/1/details/#waterfall_view_step1

**Comment by vibaldem** [comment]
We've seen this happen in our private instance when the requests come from service worker or from a different context.  The devtools user agent override only seems to apply to the current target.  
As a work around we applied the custom user agent at launch using --user-agent startup flag and that seems to apply to all requests.
