### ISSUE TITLE
Private Instance Location not showing in WPT Server UI

### ISSUE THREAD

**Issue by jenosj** [catchpoint/WebPageTest#1317]
**Dear **@pmeenan,****

We have configured a Private instance in Redhat (RHEL7) for WPT Server. We have added and New Location agent ( WPT-Agent-windows ) up and running. We are stuck in  Location not showing in WPT UI. There is no error log in Nginx. Initially, location {docroot}/tmp files are created with the location name was created. Next, we are unable to find the way to troubleshoot. Please provide some detail flow of instruction to troubleshoot this issue. Thanks in advance.

**Comment by jenosj** [comment]
Dear @pmeenan,

Please suggest us to proceed on the reported issue we are facing.

**Comment by gfx** [comment]
Do you add a new location to `locations.ini`?

For example, here is my pull-req to add a new location: https://github.com/WPO-Foundation/webpagetest/pull/1318 (it is a template file for GCP, though).
