### ISSUE TITLE
Sudden increase of WPT Tests with no Start Render reported on multiple domains

### ISSUE THREAD

**Issue by gilbertococchi** [catchpoint/WebPageTest#1323]
Hi all, since mi Dec 2019 tests complete correctly but randomly shows Error Code 99999 with some metrics reported as 0 and others with values.

Here's an example: https://webpagetest.org/result/200109_QK_05921c4ff14c62c36d9584237164ffcc/1/details/#waterfall_view_step1

It seems like SpeedIndex, Start Render and Visually Complete Time metrics fail to compute while others may.
Any idea what is going on here?

**Comment by pmeenan** [comment]
99999 is a successful page load but with content errors.  In this specific case, https://www.lastampa.it/.well-known/pubvendors.json is returning a 404

**Comment by gilbertococchi** [comment]
Hi Patrick, thanks for your reason, ok so maybe the 404 is not the reason of the missing metrics here.

Because on the Run2 there is still the 404 but the Speed Index Metrics worked: https://webpagetest.org/result/200109_QK_05921c4ff14c62c36d9584237164ffcc/2/details/#waterfall_view_step1

It's not the case on Run 1: https://webpagetest.org/result/200109_QK_05921c4ff14c62c36d9584237164ffcc/1/details/#waterfall_view_step1

Can you please advice where I can look up for errors that might case WPT to not showing Start Render, Speed Index and Visually Complete results?

<img width="479" alt="Screenshot 2020-01-10 at 10 44 49" src="https://user-images.githubusercontent.com/329023/72143075-55740800-3396-11ea-8bd1-0f20512fdbc6.png">

I see this happening randomly on the same URL with no apparent reason.

I will try to dig more on the trace to find out more...

**Comment by pmeenan** [comment]
For whatever reason, the page didn't render anything before the end of the test so no times could be calculated.  If you go to the filmstrip view you'll be able to see the white frames which is all that got recorded.

**Comment by gilbertococchi** [comment]
Thanks Patrick, can you please point me to some logs where I can dig on the reason?

This is happening randomly on many different domains etc I am testing via WPT API and I don't believe the issue is on the site itself, I suspect some Chromium change or some bug...

**Comment by pmeenan** [comment]
if you pass keepvideo=1 as a test option then the raw video of the device loading the page will be captured so you can see if it was a processing issue or a content issue.

Beyond that requires capturing chrome traces with a bunch of categories and investigating each page (by someone who knows how the pages work).
