### ISSUE TITLE
Chrome DevTools Timeline is missing some categories

### ISSUE THREAD

**Issue by andydavies** [catchpoint/WebPageTest#1327]
Open a WPT generated timeline in Chrome's Performance panel displays a view that looks like a trace from chrome://tracing has been loaded

![default](https://user-images.githubusercontent.com/427052/72992095-12c91b80-3deb-11ea-93c8-07745106ba1b.png)

Adding `disabled-by-default-devtools.timeline` to the trace categories makes it look more familiar

![disabled-by-default-devtools timeline](https://user-images.githubusercontent.com/427052/72992140-2b393600-3deb-11ea-8b54-07595623a4ab.png)

But unfortunately breaks the main thread visualisation below the waterfall

![image](https://user-images.githubusercontent.com/427052/72992197-4ad05e80-3deb-11ea-9516-2f2123b63aca.png)

https://webpagetest.org/result/200123_VH_e392acc25d69fe3814e0c5481177c0cd/1/details/#waterfall_view_step1

**Comment by andydavies** [comment]
Looks like `disabled-by-default-devtools.timeline,disabled-by-default-devtools.timeline.frame` gets most of the main browser thread info back, but I've still got a few grey segments

https://webpagetest.org/result/200310_DS_59e24d5923e0121191949e29c2138811/1/details/#waterfall_view_step1

(I've treating this as a running commentary while I debug it, will submit a PR when I get to a happy place)

**Comment by pmeenan** [comment]
Those categories are currently behind a timeline_fps category: https://github.com/WPO-Foundation/wptagent/blob/master/internal/devtools.py#L287

If I remember correctly, turning them on added enough overhead to impact the performance of the page being tested. I'll see if I can find the history on that decision but maybe it's a good time to revisit (or at least expose it to the UI, or change the timeline setting so regular timeline is enabled by default and those are added when "timeline" is enabled).
