### ISSUE TITLE
REST API ignores sensitive parameter

### ISSUE THREAD

**Issue by bramevo** [catchpoint/WebPageTest#1334]
For some reason, the sensitive parameter is ignored when using the REST API while it does work with the normal POST web portal request.
During troubleshooting I even forced "sensitive":0 on the test in the code, but this did not help to allow me to show the scripted content in the test result.

**Comment by edwincoronado** [comment]
Can you provide more information? Server version, Agents version, a sample request, and any other information that could help reproduce this issue.

**Comment by bramevo** [comment]
@edwincoronado  Hard to figure out all the versions as they run in containers on AWS. But it's easy to replicate though.

Simply trigger API using curl:
`curl -X POST https://wpt.evolane-ops.be/runtest.php \
-F 'f=json' \
-F 'url=https://www.example.com' \
-F 'label=Test' \
-F 'location=WPT_Prod' \
-F 'sensitive=false' \
-F 'k=YzTzV32GryFRYwRvBDb7zwo99ALjKTeI' \
-F $'script=navigate\thttp://www.example.com\n'`
OR using:
sensitive=0

If you check the test result you will see in the test "Scripted test" in bold and it is not possible to view the code as it would be when started from the GUI and leaving "Script includes sensitive data" unchecked, when it would show "Scripted test" in yellow and make it clickable.

**Comment by pmeenan** [comment]
The scripts are only visible to the owner of the test (the user that submitted it). When a test is submitted through the API it is orphaned and not linked to your browser session so you can't see the script.  For private instances it might be worthwhile to make that configurable so sites can opt-into making non-sensitive scripts visible to anyone.

**Comment by bramevo** [comment]
@pmeenan Ok, but wouldn't it make more sense to use the sensitive parameter for that? Because that one will also hide it for the owner of the test. If somehow, that parameter can be used when using the API and overwrite standard behaviour, that would already solve it.

**Comment by pmeenan** [comment]
It's risky to change the default behavior. Private instances like SpeedCurve that have multiple users would also be impacted and may be running tests without the sensitive parameter because of previous protections.  A setting to change the default behavior but still hide when sensitive is specified is what I'm proposing.

**Comment by bramevo** [comment]
@pmeenan The alternative might indeed be confusing. (Although you could force undefined to true for the parameter to avoid showing this content when undefined). And only show it when it's set to 0|false. But still, if people made a mistake, it might still start to show the content.
So you propose a new setting somewhere to overwrite it? Where exactly?
