### ISSUE TITLE
AB-test site provides different results in chrome and firefox

### ISSUE THREAD

**Issue by Jospaul** [catchpoint/WebPageTest#1335]
We have an AB test running for our site and is currently live in production. Below is the expectation - 
* Select a product
* Clicking on Add to Bag
* Shows a Modal overlay/Popup on the page to proceed to checkout

Previous experience - On clicking add to bag a mini modal appears on the right corner with the updated bag count to proceed to checkout.

Currently when a test is run with Chrome we are getting the previous experience, whereas in firefox we get the intended experience. We are able to get the correct expectation when we try to manually replicate the issue on Chrome in our desktop. The problem seems to be only on webpagetest.

Below are 2 identical tests run on Chrome and Firefox for reference of the issue - 
Firefox - https://www.webpagetest.org/result/200224_1R_3399f5b4db9f6b53e638db15212379fb/
Chrome - https://www.webpagetest.org/result/200224_JN_8d7aff72c6e6b60da039cec6c2e73970/

**Comment by Jospaul** [comment]
We were able to get it working through chrome if we change the userAgent.

**Comment by pmeenan** [comment]
How does your AB selection work? If it depends on the user agent string, is it handling the PTST version of the UA string? How do you force a specific branch?

**Comment by pmeenan** [comment]
WPT has a "preserve user agent string" option if you want to use the default UA string and not append PTST/xxx to it.  Sounds like your AB platform isn't handling the UA strings as you'd want

**Comment by Jospaul** [comment]
Currently the feature is deployed in production and we exercise this by a
get parameter with the url.
I tried with preserving the user agent string and it is working with Chrome
with that. However, it was working on firefox with the PTST/*** in it.

Thanks for your response. Currently we will proceed with the user agent
modification.

Regards,
Jospaul Mahajan Prakash
