### ISSUE TITLE
Caching issues with webpagetest-server itself

### ISSUE THREAD

**Issue by bramevo** [catchpoint/WebPageTest#1338]
We placed webpagetest-server docker container behind a CDN and noticed that caching headers where frequently missing.
Our first idea was to use the existing method that works for www/work/getwork.php which is:

    header("Cache-Control: no-cache, must-revalidate");
    header("Expires: Sat, 26 Jul 1997 05:00:00 GMT");

So we added this ourselves to following scripts:

www/install/install.php
www/getLocations.php
www/getTesters.php
www/results.php (Only for running.inc inclusion)
www/testlog.php

Should I create a pull request with this or should we set these headers in another way? For results.php the only way is to add it specifically for running.inc but the headers for the other pages could be set in a different way (maybe htaccess) or by including a file that sets these headers? For example a new file called cache_headers.inc ?

**Comment by pmeenan** [comment]
I'm not entirely sure it works as expected but I have my php.ini configured with 

session.cache_limiter = nocache

I think that's usually the default but what I don't know is if that will always set the headers or only when a session is used.

There are a few files that set it explicitly to allow caching (particularly for the waterfall images).  If there isn't a good way to get the defaults working in php then modifying common.inc to add the nocache header is probably the best place.  It should get used by any page that outputs json or html but not the support entrypoints like for images (I think).

**Comment by bramevo** [comment]
Problem with caching is that you do not want to disable it by default but you do want to specify what can (not changing dynamic content) and cannot be cached (intermediate responses). For example install page shows connected testers so you never want to cache this. Same thing for running test response, because otherwise you will never see the response because the running output is cached instead. While the finished test is a good example of a page you want to cache because this will not change.
So setting it should be per resource, but you could do it by just including a new inc file.

Just noticed that if you activate multiple runs, that the in between results also shouldn't get cached. This is also one that needs to be changed inline.

**Comment by pmeenan** [comment]
Other than the static generated content (waterfalls, thumbnails), nothing should generally be cached in the case of WebPageTest that comes from the php code. The places where it should allow caching already explicitly add the expiration header.  i.e.: https://github.com/WPO-Foundation/webpagetest/blob/master/www/thumbnail.php#L70

**Comment by bramevo** [comment]
Not entirely true. As a web performance engineer, our focus is on caching and this includes way more than only the static content. For example the homepage, this is a page which never changes, so why wouldn't you cache this page? Finished test results should also never change right, so perfectly cacheable. Same for the about page -> never changes.

So besides caching static content, it is also important to specify if the other pages are cacheable or not and set headers accordingly.

**Comment by pmeenan** [comment]
But the home page DOES change, depending on the location availability and queues.  Finished tests results MAY change if the php code is updated to fix issues or add features.  Same goes for the about page.

You're obviously welcome to do whatever you'd like with your private instance but generally the safest mode of operation is to let the static files accessed directly by the server (screen shots, etc) be cached on the browser but keep most of the php code as being served dynamically.  The php code itself has internal caching to avoid re-doing expensive compute and versions things like the TTI calculations so it is only re-run if the code changes.

**Comment by bramevo** [comment]
You are correct about the home page. Forgot the location and device stuff.
If PHP code is updated, a purge of the cache is required when data is cached. But that is the same thing for static content. Those might also be updated and require cache invalidation.

We do run our own private instance but prefer to keep it in sync, especially for standard things. Why we think this is a standard issue: If you activate any CDN in front of the current webpagetest source (or any other caching layer), it will cache the webpages because of missing cache-control headers and break the website. Yes you can fix this on the caching layer using settings, but we feel that best practices is to build cache-control in the application.

Is it useful to create a pull request for this or should we just keep it in a fork?

**Comment by pmeenan** [comment]
A PR would be useful if we can nocache the bulk of the pages and only explicitly extend caches for the pages where we know it is safe.  If we put a nocache in common.inc and overwrite the header ($replace=true) for the known-safe cases then that should work.

There is no way to "purge" the browser cache so I'd want to consider VERY carefully before making quasi-cacheable content cacheable.  Possibly completed test result pages and JSON but I'd want to save that for a later round.
