### ISSUE TITLE
Server pushed assets break redirect chain and impact TTFB calculation

### ISSUE THREAD

**Issue by crockercliff** [catchpoint/WebPageTest#1341]
While admittedly an edge case, we have seen issues where TTFB was artificially lower due to the fact that the redirect chain was "interrupted" by pushed assets. Here is an example of a comparison view for the same page when assets are pushed vs. not:
https://wpt1.speedcurve.com/video/compare.php?tests=200213_C3_b66602ce06da3a000e124e6ef946c98d%2C200211_1X_1ccdefa08edc296da0593931bca7bb7d&thumbSize=200&ival=100&end=visual

Expected behavior: Pushed assets would be ignored (or included?) in TTFB calculation when they occur within a chain of redirects.

**Comment by pmeenan** [comment]
Should be easy enough to just skip over any pushed resources when looking for the first request.
