### ISSUE TITLE
 Request for metrics that are inclusive to Assistive Technology

### ISSUE THREAD

**Issue by scottjehl** [catchpoint/WebPageTest#1369]
Also posted over at lighthouse https://github.com/GoogleChrome/lighthouse/issues/11049

Related blog post: https://www.filamentgroup.com/lab/a11y-ready/

**Feature request summary**

It would be useful to know when Assistive Tech is able to interact with and communicate page content so that that timing can be factored into existing metrics that represent page "readiness". Measurements that note or approximate the time when the accessibility tree is built would be interesting to see and understand, and as Léonie's Watson's [tweet](https://twitter.com/LeonieWatson/status/1260270620518035456) mentions, the time of the first accessibility API query as well.

It'd be interesting to know which existing metrics are not relevant to Assistive Tech, and what is blocking AT from being ready sooner. It'd also be useful to know, in an SSR scenario, is the accessibility tree created initially one way and later "hydrated" into a much different state?  

**What is the motivation or use case for changing this?**

To see metrics that measure when a page is usable to all users, including those using AT.

[AB#141023](https://dev.azure.com/catchpointsystems/3530e88b-329c-4a68-a776-27327b83ff68/_workitems/edit/141023)

**Comment by pmeenan** [comment]
This might have to be an option specific to when a test is run (to enable accessibility).  I don't think the AT stuff happens unless something attaches to the browser to enable it (screen reader, etc) and it likely changes how the browser operates.

It looks like the dev tools protocol [exposes AT](https://chromedevtools.github.io/devtools-protocol/tot/Accessibility/) controls so it should be easy enough to add (may require some trace events to see the AT tree mutations though) but it doesn't look like something that should be enabled and collected by default.  Not sure if it will be possible on non-Chrome browsers.

**Comment by scottjehl** [comment]
Sounds really interesting, Pat. Thanks for your consideration. Excited to see what you find.

**Comment by scottjehl** [comment]
@pmeenan do you envision this could be written as a custom metric to test it out first?

**Comment by pmeenan** [comment]
I don't think so. Maybe if I at least provide a way to enable accessibility but then you'd need to inject a script that polled for the AT and then a custom metric that extracted when it became available.  There's not currently any way that I know of to enable accessibility on the command-line.  That said, that might be a light-weight way to at least test it out while we try to figure out what trace events there are for AT.

**Comment by scottjehl** [comment]
Okay.
One thing I wonder about is if there's a way to, manually even, track when say, VoiceOver begins to read the page aloud, which could come some amount of time after the accessibility tree is available. For example, there's a setting (maybe a default?) where VO announces the page progress... you can enable VoiceOver's text captions to visually see those updates as well, and when they finish it begins to speak the page content.

 You can see both of those happening in this video https://www.youtube.com/watch?time_continue=17&v=EnmWUj4XKGg&feature=emb_logo


This strikes me as much later than domcontentloaded, when the Accessibility tree might be available to VO. It seems conservative in when it deems the page ready (long after it's visibly rendered). It makes me wonder if your test run could boot up safari or iOS with Voiceover on, and then let the timeline capture do the work of telling us when certain updates occur. Maybe this would be more useful than the tree availability?

**Comment by pmeenan** [comment]
Only if there's actually a way through code to know that VO is being read aloud. iOS remote debugging capabilities are generally much more limited than Chrome's so I'm not hugely optimistic.

Recording device audio might be possible but we'd need to figure out a way to align it with the test start.

**Comment by scottjehl** [comment]
Hi @pmeenan and @tkadlec !

We're working on a roundup including updates on how performance incentivization and metrics are evolving, so I was curious if you have any new thoughts on how this metric might fit into WPT.

Thanks for all the great work lately!

**Comment by tkadlec** [comment]
Hey @scottjehl! Still pretty interested in this. Watching the Lighthouse discussion pretty closely to see what comes out of it. We may be able to play around/prototype something here, but if the Chrome team comes up with a more solid/robust way of signaling relevant information, that would push this much higher up our queue.
