### ISSUE TITLE
Add an option to force TTFB to a fixed value

### ISSUE THREAD

**Issue by pmeenan** [catchpoint/WebPageTest#1435]
Eliminate Back-end variability in the base document (not subrequests):
* Add a test option to force a specific TTFB
* At the end of the test, change the "startTime" that everything is based off of to be the first byte time - the configured TTFB
* Eliminate the connection set-up timings from the first request
* Make sure to propagate the timing adjustment to all of the timings in page data, requests and video frames

[AB#140939](https://dev.azure.com/catchpointsystems/3530e88b-329c-4a68-a776-27327b83ff68/_workitems/edit/140939)

**Comment by tkadlec** [comment]
Issue #1403 looks to be trying to solve the same issue from a different angle.

**Comment by tkadlec** [comment]
Moar community feedback: https://twitter.com/calinoracation/status/1428039160418365440

**Comment by swcarter007** [comment]
I would love to see this feature.  It would make comparison of charts so much easier if you could isolate the BE time out of the equation temporarily.

**Comment by nhoizey** [comment]
It would be great to be able use here the new CrUX TTFB value @tkadlec announced: https://twitter.com/tkadlec/status/1523704210956509184

(But also any user submitted value.)
