### ISSUE TITLE
Disabling JS setting causes test to timeout and fail

### ISSUE THREAD

**Issue by Nooshu** [catchpoint/WebPageTest#1495]
## Description
Checking the disable JS option in advanced settings causes the test to fail.

### Steps to reproduce
Run a test on a site with setting enabled.

### Expected result
Test should run, but JS not enabled

### Actual result
Tests fail with "First View: Test Error: Page Load Timeout"

Test examples:
- [GOV.UK JS disabled - fails](https://www.webpagetest.org/result/210516_AiDcQW_c389977a7112a167cbdaab8242f67bf0/)
- [GOV.UK JS enabled - passes](https://www.webpagetest.org/result/210516_AiDc2P_cc2c52e28c142ad4f9942686cd43b3bd/)
- [netcentric.biz JS disabled - fails](https://www.webpagetest.org/result/210516_AiDcMG_069a43211a22ff5acd53736094605337/)
- [netcentric.biz JS enabled - passes](https://www.webpagetest.org/result/210516_AiDcKT_2605e6ff4f2e80f05e9a30318e0526ad/)

[AB#140938](https://dev.azure.com/catchpointsystems/3530e88b-329c-4a68-a776-27327b83ff68/_workitems/edit/140938)

**Comment by pmeenan** [comment]
Hmm.  I may have to remove that feature and rely on just letting users block external js files.

The initial navigation is done with JS to align the video frames with the navigation and to align everything on a RAF boundary. For Chrome and Safari I may be able to fall back to dev tools navigation but the video alignment is going to be racier.

**Comment by Nooshu** [comment]
Sounds like it may be the only option then. I'm wondering if this could be documented somewhere?

"We've removed this functionality but the alternative is x" Where x is blocking via scripting / block / SPOF etc...
