### ISSUE TITLE
Indicate if the main document is valid HTML

### ISSUE THREAD

**Issue by rik** [catchpoint/WebPageTest#1499]
## Feature Request Summary
Run a HTML validator as part of a test.

### What's the motivation or use case for the change/feature?
Pages with HTML errors can cause sneaky issues such as:
- Closing the `<head>` earlier than expected which can change download priorities ([highlighted by @csswizardry](https://twitter.com/csswizardry/status/1349400099647090694))
- Rendering differences between DOM after HTML parsing and DOM after JS manipulations (see https://github.com/mozilla/addons/issues/14200)

**Comment by tkadlec** [comment]
Love that Mozilla example!!

If we added this, where would you expect to see it @rik?

**Comment by rik** [comment]
Good question… hum…

What about a warning/error symbol on the Content tab and the list of errors on that page?

**Comment by rik** [comment]
So now, I think this would fit well in the new "HTML diff" page 😉

**Comment by stoyan** [comment]
yeah, @tkadlec pointed to this issue in the light of the html diff. Especially when attempting to run prettier on invalid html.

Worth revisiting this feature for sure
