### ISSUE TITLE
Confusing test URL link in test history page

### ISSUE THREAD

**Issue by kgrz** [catchpoint/WebPageTest#1501]
The `URL` column shows the URL that was tested, but the link (fwiw, the old design made it much clear that it's a link), when hovered on, doesn't make it clear that it's clickable. It shows a text selection pointer rather than a link pointer. And it's not clear at first glance that the link actually navigates to the test result unless checked on the browser status bar. I wasn't able to capture the cursor in the screenshots, but here's an example anyway:

<img width="1290" alt="Screenshot 2021-06-10 at 1 16 32 PM" src="https://user-images.githubusercontent.com/400299/121486681-fa14d200-c9ee-11eb-9f6a-dc69538b27e3.png">

https://user-images.githubusercontent.com/400299/121486971-419b5e00-c9ef-11eb-887e-687e72abc211.mov

**Comment by tkadlec** [comment]
Thanks, @kgrz. Agree....it's not super clear here. We've got a pretty significant revamp coming for the test history page that should take care of this.

I'll let you know here when there's an update.

**Comment by scottjehl** [comment]
@kgrz thanks - issue here explains updates on the way for history https://github.com/WPO-Foundation/webpagetest/issues/1989
