### ISSUE TITLE
Ability to filter/highlight requests based on search criteria

### ISSUE THREAD

**Issue by tkadlec** [catchpoint/WebPageTest#1502]
## Feature Request Summary
Provide the ability to either highlight items in the waterfall and/or filter the Request Details table based on search criteria.

### What's the motivation or use case for the change/feature?
Chrome Dev Tools provides the ability to search through network requests based on a number of criteria: a given response header, domain, url, etc.

![Screen Shot 2021-06-10 at 8 31 37 AM](https://user-images.githubusercontent.com/66536/121533885-53b4d680-c9c6-11eb-829c-b46c029cda0d.png)

It's super handy for zeroing in on a specific resource, finding any items without GZip applied, etc. 

Seems like a slick idea to add something similar to WPT.

**Comment by rik** [comment]
In that spirit, maybe a low tech implementation or a first step could be to have real text in the waterfall so browsers can find that text?

**Comment by tunetheweb** [comment]
Came here to open that. Definitely agree with @rik that real text would be handy but suspect that's a more complex problem.

In meantime what would be nice is ability to have a highlight input box, so you could search for "jquery" and it would redraw the graph with all instances of jquery highlighted somehow (e.g. like redirects are highlighted in yellow). Given you already highlight redirects like this this might be fairly simple to implement? Says he never having done any front end development on WPT... 😁

**Comment by ebizindia** [comment]
Being able to search for a text (like jquery) in the list of resources will be very useful. Filtering will be even better IMHO.
