### ISSUE TITLE
API Endpoint for searching test history

### ISSUE THREAD

**Issue by tkadlec** [catchpoint/WebPageTest#1534]
## Feature Request Summary
Add an API endpoint for searching through test history, scoped to the request's API key. See https://twitter.com/josephscott/status/1438246738972663809

**Comment by josephscott** [comment]
To flush this out a bit more.  It would be helpful to have an API end point that I give a key and search term(s).  Currently the two main fields I'd like to search are the URL and label.  However, I could see being able to include a date range and location parameters as potentially useful as well.  All search parameters would only apply to tests submitted by the provided key.

The return data could look similar to the fields listed at https://app.webpagetest.org/ui/wpt/testhistory - and the test submission response, namely:

- test id
- URL tested
- label
- location
- run date
- jsonURL
- xmlURL
- userURL
- summaryCSV
- detailCSV

In both XML and JSON formats, depending on the [`f` value provided](https://docs.webpagetest.org/api/reference/#response-format).

With a test history of 13 months, and searching by API key and search terms, I'd be able to quickly put together a reference list for internal tooling that links out to the various tests for a given URL or label.
