### ISSUE TITLE
Pretty new logo means these privateInstall overrides no longer work

### ISSUE THREAD

**Issue by rposbo** [catchpoint/WebPageTest#1539]
https://github.com/WPO-Foundation/webpagetest/blob/cded378f8e6f8bf3385512f1588f36ab0181f448/www/head.inc#L54

The logo is a `img`, so this background swap doesn't seem to change the UI

![image](https://user-images.githubusercontent.com/316233/134006782-2111d63f-10dc-4099-9cfe-19ab718abd36.png)

[AB#140914](https://dev.azure.com/catchpointsystems/3530e88b-329c-4a68-a776-27327b83ff68/_workitems/edit/140914)

**Comment by tkadlec** [comment]
Whoops! Good catch.

Also thank you for calling our logo pretty. We agree. :)
