### ISSUE TITLE
Archive failed tests to avoid filling up disc [private instance]

### ISSUE THREAD

**Issue by rposbo** [catchpoint/WebPageTest#1565]
## Feature Request Summary

Archive and delete blatantly old tests that are considered `waiting` or `running`; e.g., is the test older than `$MAX_DAYS`? Archive and Delete. `$MAX_DAYS` is defined in `archive.php` but never used (nor is it referenced anywhere else, globally).

https://github.com/WPO-Foundation/webpagetest/blob/master/www/cli/archive.php#L287

### What's the motivation or use case for the change/feature?

I run several thousand tests a day (so 10k+ runs) and need to aggresively archive them to S3 to avoid disc space filling up. I have `archive_days` set to a low number (used to be `0` but that now breaks, due to a check in `archive.php` that equates that to `false`!) - 0.1 - however I am seeing disc usage continue to increase which will result in total failure.

![image](https://user-images.githubusercontent.com/316233/135860104-867c80a2-26f1-438b-b812-97f9bd456c2b.png)

(The reason for the tests halting isn't clear - I'll raise another issue when I figure that out!)

[AB#140409](https://dev.azure.com/catchpointsystems/3530e88b-329c-4a68-a776-27327b83ff68/_workitems/edit/140409)

**Comment by tkadlec** [comment]
Thanks @rposbo! This is helpful even without the PR. :)
