### ISSUE TITLE
Ability to add artificial delay to specific requests

### ISSUE THREAD

**Issue by tkadlec** [catchpoint/WebPageTest#1646]
It would be nice to have the ability to insert artificial delay into specific requests to be able to test browser behavior or to test race conditions.

It's a bit of an edge case, I know, but Steve Souders used to have a service that did something like this and today you can do some of with https://slowfil.es/, and I've used both a bunch. Might be interesting to have it baked in at some point.

**Comment by kevinfarrugia** [comment]
I have come across a couple of use-cases for this feature. In some cases I am able to find a workaround using the _Find and Replace Text_ experiment as suggested by @scottjehl but when the text is inside a script file, then it is not possible to use the Find/Replace.

Example use case:
- Some content on a webpage is dependent on the logged in/out status. If the authentication request (XHR) takes long, how does this affect rendering and CWV? Does it have a snowball effect on other requests?

**Comment by scottjehl** [comment]
I'm not sure, but I think our efforts to make some existing experiments work on more content types than HTML could provide one workaround for @kevinfarrugia's followup. But I think a global time-based delay would be awesome.
