### ISSUE TITLE
Slow TTFB when req is served from Service worker cache

### ISSUE THREAD

**Issue by abelhbeyene** [catchpoint/WebPageTest#1652]
## Description
I want to compare TTFB when a request is served by a Service worker so  I have setup a script that starts the SW, creates a cache and makes a final req which should be served from cache. However, the TTFB is exactly the same whether I have SW or not. Carrying out the same journey on Chrome consistently shows me 10ms - 15ms instead of 500ms+.

### Steps to reproduce
The script that I am using:
```
logData 0
navigate https://example.com/page1 // activate sw
navigate https://example.com/page1 // sw caches the req
execAndWait document.body.innerHTML=''
sleep 2
logData 1
navigatehttps://example.com/page1 // should be served from cache
```
Here is a sample run: https://www.webpagetest.org/result/211220_BiDcXD_bafaa147a5737ce6114acef51eb77078/

### Expected result
I expect the TTFB of the last navigate request < 100ms. Testing this journey in chrome results in 10ms - 15ms.
Chrome slow 3G: 
<img width="63" alt="image" src="https://user-images.githubusercontent.com/12272815/146965247-bb4ce5e5-a16c-48f2-805d-21fa69db29bc.png">

### Actual result
TTFB is 700ms+

### Related issues?
No

**Comment by tigt** [comment]
Does your Service Worker call `self.skipWaiting()`? (I tried looking at its file in your result, but got 403’d.)

**Comment by abelhbeyene** [comment]
Yes, it does. Unfortunately, its an internal env so I can't share the link to the file on here. 
<img width="507" alt="image" src="https://user-images.githubusercontent.com/12272815/152777376-106cc46a-adfe-4673-baaa-24ad05c372c2.png">
