### ISSUE TITLE
Show more info about test run in filmstrip label area, for use in screenshots

### ISSUE THREAD

**Issue by scottjehl** [catchpoint/WebPageTest#1700]
Thanks a suggestion is having the test details also displayed closer to the new filmstrip view would be great so we can do screenshots of the filmstrip along with test parameters

via https://twitter.com/centminmod/status/1487059801624309760?s=20&t=i1C9kiCV6Y1QQKzp_3UkPQ

**Comment by tkadlec** [comment]
@scottjehl For version, what do you think about pulling it right next to the icon, like thus
![Screen Shot 2022-01-28 at 11 20 21 AM](https://user-images.githubusercontent.com/66536/151592566-280dc3df-8e3a-4688-a0f2-820a99144044.png)
