### ISSUE TITLE
Latest release image (22.01) isn't on dockerhub

### ISSUE THREAD

**Issue by mikegeyser** [catchpoint/WebPageTest#1706]
## Description
The last release of webpagetest/server ([v22.01](https://github.com/WPO-Foundation/webpagetest/releases/tag/22.01)) doesn't seem to have been pushed to docker hub. The last available release [tagged on dockerhub](https://hub.docker.com/r/webpagetest/server/tags) is [21.07](https://github.com/WPO-Foundation/webpagetest/releases/tag/21.07).

### Steps to reproduce

```
> docker pull webpagetest/server:22.01

Error response from daemon: manifest for webpagetest/server:22.01 not found: manifest unknown: manifest unknown
```

### Expected result
That it fetches the image for that release version.

### Actual result
The latest image isn't available. The latest seems to be 21.07, or another build from the same period.

### Related issues?
I don't think there are any related issues. The `webpagetest/agent` release [was correctly tagged](https://hub.docker.com/r/webpagetest/agent/tags) to 22.01.

**Comment by mikegeyser** [comment]
I hope this issue is ok? I know that this isn't strictly speaking a WPT bug, but it isn't an enhancement either. I also know that we could fork and build the image ourself, and publish it internally, but that really isn't an appealing option to us. The ideal would just be to be able to rely on `docker pull webpagetest/server:latest` in our build pipeline.

**Comment by mikegeyser** [comment]
Hi folks, just following up on this. Is there something wrong with how this issue was logged?

**Comment by tkadlec** [comment]
Hey @mikegeyser! Sorry for the radio silence! Your issue is logged perfectly fine. :) We've been having issues with the Docker script for the server and likely need to rewrite it. I don't have a timeline on when exactly we'll have that taken care of, but will update here as soon as we do.

**Comment by alexandrul** [comment]
I've pushed my version of `22.01` [here](https://hub.docker.com/repository/docker/edutu/wpt-server-demo/tags) since I have no idea when the agent will include the fix for the missing repeat view when using `21.07`.

**Comment by mikegeyser** [comment]
Hi folks, it seems as if all of the container images have now been removed from dockerhub. I'm not sure why it happened, but it's been very disruptive and is a very disappointing turn of events. We've come to rely on webpagetest in our environment (where everything runs inside a kubernetes cluster), and even though they were out of date - we thought using the 'official' container images would be safer than trying to write our own.

Related: https://github.com/WPO-Foundation/wptagent/issues/558

**Comment by tkadlec** [comment]
Hey gang! We're really sorry about the mixup here. The agent is back up on Docker now.

The server looks like we need a little work to sort out yet. :/

**Comment by mikegeyser** [comment]
Thanks @tkadlec!

**Comment by anthonymunene** [comment]
Hi @tkadlec are there any plans to provide an updated wepagetest server for docker

**Comment by tkadlec** [comment]
Yup! There's actually been some very recent work on that if you want to play with a bit. https://github.com/WPO-Foundation/webpagetest/tree/master/docker/local

**Comment by sharksforarms** [comment]
Hi, I noticed the server image is no longer on dockerhub: https://hub.docker.com/u/webpagetest is this intended?
