### ISSUE TITLE
addHeader/Custom Header to optionally only set on document request

### ISSUE THREAD

**Issue by delambo** [catchpoint/WebPageTest#1744]
## Feature Request Summary

Add an option to send a Custom Header on the document request only. The current feature adds custom headers to _all_ requests.

### What's the motivation or use case for the change/feature?

When you add a Custom Header to the UI or use the scripting API to `addHeader`, it adds the header to _all_ requests. For a moderately complex site, like The New York Times, that breaks a lot of CORS requests. For example:

```
Access to XMLHttpRequest at 'https:\/\/int.nyt.com\/svc\/time' from origin 'https:\/\/www.nytimes.com' has been blocked by CORS policy: Request header field x-nyt-int-cwv-ads is not allowed by Access-Control-Allow-Headers in preflight response.
```

I'm not sure about the use case for sending a custom header to _all_ resources in a page load. It makes more sense to only send a custom header along with the document request.

**Comment by andydavies** [comment]
Related: https://bugs.chromium.org/p/chromium/issues/detail?id=1229598

DevTools API only allows setting the header for all requests ATM
