### ISSUE TITLE
Map Chrome DevTools Recorder to WPT Custom Scripting?

### ISSUE THREAD

**Issue by tkadlec** [catchpoint/WebPageTest#1772]
## Feature Request Summary
Now that you can export a Recorder session as JSON (https://twitter.com/JecelynYeen/status/1499401441160482830), it might be interesting to dig in and see how much of this we could map to WPT commands.

Then I could see us adding an "import recording" feature that would take the JSON, convert it to a WPT script and run the test.

### What's the motivation or use case for the change/feature?
It's cool and it makes WPT custom scripting a lot more approachable.

**Comment by addyosmani** [comment]
I would absolutely love to see support for DevTools recording imports happen :) 

If you explore this feature, you might find our replay library interesting. It provides an API to replay and stringify recordings created using the recorder: https://github.com/puppeteer/replay.

**Comment by tkadlec** [comment]
Thanks for sharing, @addyosmani!

We've actually started on a script here: https://github.com/WebPageTest/Recorder-To-WPT-Script. 

SUPER experimental and rough at the moment—we need to keep testing and refine a bit—but it's been pretty promising so far.
