### ISSUE TITLE
Deep Link to Perfetto for Traces

### ISSUE THREAD

**Issue by tkadlec** [catchpoint/WebPageTest#1899]
Right now, WebPageTest brings the Perfetto UI directly into our codebase. To shed that, and make sure we're always pointing at the latest versions, @mmocny suggested on Twitter (https://twitter.com/mmocny/status/1529468008665690113) that we deep link to the UI (https://perfetto.dev/docs/visualization/deep-linking-to-perfetto-ui)

I played with this a little and had a rough prototype working in no time, so implementation wise it's super straightforward. We should do this. :)

**Comment by mmocny** [comment]
🎉 🥳 🎂
