### ISSUE TITLE
A significant portion of HTML content was generated by JavaScript after delivery on a static site

### ISSUE THREAD

**Issue by kevinfarrugia** [catchpoint/WebPageTest#1945]
## Description
> A significant portion of HTML content (2kb, 7% of total HTML) was generated by JavaScript after delivery.

The above is being reported even if the HTML does not change and the only HTML changes are third-party scripts added using GTM or similar.

### Steps to reproduce
Test URL: https://www.webpagetest.org/result/220602_AiDc9J_9EZ/2/experiments/

### Expected result
Do not think it should report this as an Opportunity.

### Actual result
Getting this opportunity:
> A significant portion of HTML content (2kb, 7% of total HTML) was generated by JavaScript after delivery.

**Comment by kevinfarrugia** [comment]
It would be helpful if it is possible to know what the generated HTML is or at least some examples.

**Comment by rik** [comment]
Maybe this opportunity could exclude `<script>` tags from the heuristic or increase the threshold?

**Comment by tkadlec** [comment]
> It would be helpful if it is possible to know what the generated HTML is or at least some examples.

This is a great suggestion! We've talked a bit about it internally too and hope to get something like this in place.

> Maybe this opportunity could exclude <script> tags from the heuristic or increase the threshold?

I think bumping the threshold might make sense here. Got suggestions on what you would think would be reasonable @rik?

**Comment by rik** [comment]
I'm not sure what threshold would work best. Ignoring `<script>` would be my first try to improve the relevance of this opportunity. And after that, see if people report other false positives.
