### ISSUE TITLE
Get a sync on issue alert when raising a Bug in this repo

### ISSUE THREAD

**Issue by tunetheweb** [catchpoint/WebPageTest#1948]
## Description
Raised a bug and got this email alert:
![8D0594E6-AAFA-4444-9795-FF5D3E8E6B37](https://user-images.githubusercontent.com/10931297/171620505-910dfbf1-59a9-486e-ad18-515bd404a6a1.jpeg)

Looks like the GitHub Action was run twice:
- https://github.com/WPO-Foundation/webpagetest/actions/runs/2427921500 (this one failed with `HttpError: Bad credentials`)
- https://github.com/WPO-Foundation/webpagetest/actions/runs/2427921668 (this one succeeded)

### Steps to reproduce
Raise a bug (as a non-maintainer I presume?).

### Expected result
No error email sent.

### Actual result
Error email sent.

### Related issues?
Not that I could see when searching for “sync”

**Comment by tkadlec** [comment]
Ick. Sorry about that. :/ Looks like the sync action is being finicky. Will take a peek and see if I can track down what's up there...seems to be failing rarely, but enough to be annoying.
