### ISSUE TITLE
Provsion to delete some test results

### ISSUE THREAD

**Issue by ebizindia** [catchpoint/WebPageTest#1971]
## Feature Request Summary
Provision to delete some test results. I will like to tick on some checkboxes in the test history and delete these.

### What's the motivation or use case for the change/feature?
We run some tests by mistake. Example: For a website with UK audience, I ran a test from Virginia test centre. This can confuse us while reporting to the client. Similarly, I ran a test but gave it a misleading label. I will like to see these tests taken out from my history.

**Comment by scottjehl** [comment]
This is part of #1989
