### ISSUE TITLE
Bug: Priority Hint experiment actually applies to links, images, scripts, but text just says images

### ISSUE THREAD

**Issue by scottjehl** [catchpoint/WebPageTest#2031]
just a text edit here
<img width="557" alt="image" src="https://user-images.githubusercontent.com/214783/173158570-28ae247c-5847-4f2d-8053-dfd153caa358.png">

**Comment by rockeynebhwani** [comment]
@scottjehl - Is this just a cosmetic issue or functionality itself doesn't work. I wanted to add fetchpriority="high" for a JS file but it didn't work. 

Page URL - https://rothys.com/products/the-point-black-solid

My first WPT run - https://www.webpagetest.org/result/220709_AiDcXA_4KA/

In this run, you will that main.js (https://cdn.shopify.com/s/files/1/0877/4986/t/433/assets/main.js?v=34444766995290197441657047423) is loaded with MEDIUM priority

I wanted to add fetchpriority="high" for main.js so I went to Advance experiments section and added 

`https://cdn.shopify.com/s/files/1/0877/4986/t/433/assets/main.js?v=34444766995290197441657047423/i_high` and ran the experiment

This is the URL for run with experiment - https://www.webpagetest.org/result/220711_AiDc38_2W0/1/details/#waterfall_view_step1

But in this run, I don't see it working. Also, this link is not showing the experiment at the top.
