### ISSUE TITLE
Advanced mode always expanded

### ISSUE THREAD

**Issue by ebizindia** [catchpoint/WebPageTest#2032]
## Feature Request Summary
I want the Advanced mode to be auto-expanded (for me) as I always use this mode and not the basic mode. There must be many like me.

### What's the motivation or use case for the change/feature?
As I always use the Advanced mode to run my tests so that I can apply a label, change the test location, number of tests, etc, I have to first expand the "advanced mode" and then enter my options. I am sure many users are doing the same. Providing an option to always expand the Advanced mode will save some extra work. :)

Thank you for considering this.

**Comment by tkadlec** [comment]
This is a great suggestion and I'd love to have this be associated with each account (setting/cookie/etc). 

In the meantime, if you go to https://www.webpagetest.org/?advanced, it will open the home page with the advanced configuration opened by default.

**Comment by ebizindia** [comment]
This is pretty cool for the time being. Is there a place where I can see all such options/parameters?

**Comment by tkadlec** [comment]
There isn't really, no. We're working on making the most useful of those more available in the UI, but we should probably get a list of the others together at some point too.

**Comment by ebizindia** [comment]
I think there are a few URLs that can be directly called. I saw a couple in
some talk but did not take a note.

Please see if we can get some such URLs listed somewhere.
