### ISSUE TITLE
PerformanceObserverForWindow incorrect due to WPT usage of PerformanceObserver

### ISSUE THREAD

**Issue by tdresser** [catchpoint/WebPageTest#2061]
Here's the har for example.com
https://www.webpagetest.org/export.php?bodies=1&pretty=1&test=220616_AiDcM5_9XV

This is likely because WPT uses PO to measure performance. Ideally we'd be able to do this based on the trace without injecting script?

**Comment by tkadlec** [comment]
Hey @tdresser —sorry, could you give a little more detail on the issue you're seeing to help us dive in?

**Comment by tdresser** [comment]
Sorry, that was pretty cryptic.

See the graph at the bottom of https://chromestatus.com/metrics/feature/timeline/popularity/2188 for a timeline of the % of sites using PerformanceObserver. It spiked at the beginning of 2021, I suspect due to a WPT change where WPT injects JS which uses PerformanceObserver.
