### ISSUE TITLE
Collapsed navigation menu is still accessible (and visible)

### ISSUE THREAD

**Issue by beep** [catchpoint/WebPageTest#2062]
## Description
Currently waiting for a test, and I noticed the “collapsed” navigation menu is visible offscreen in Firefox (macOS), and focusable with the keyboard.

### Steps to reproduce

1. Start a test from Firefox (macOS) at a viewport width around 1280px.
2. Scroll to the right, or press the tab key.

Here’s are [my (at the time of writing, in-progress!) test results](https://www.webpagetest.org/result/220616_AiDcES_EZ7/); here’s [a quick screen recording (10MB, QuickTime)](https://user-images.githubusercontent.com/124493/174177042-fa7937c1-97aa-45c8-8436-931783cedd9b.mov).

### Expected result
The navigation menu shouldn’t be visible or focusable when collapsed, and the page shouldn’t have a horizontal scrollbar.

### Actual result
The navigation menu was visible and focusable when collapsed, and the page has a horizontal scrollbar.

### Related issues?
None that I could find. (Apologies if I missed them, though!)

**Comment by scottjehl** [comment]
Thanks @beep!

Huh, yeah you're right. Interesting. It seems like some browsers (chrome, Safari) don't seem to care what the `display` value is on children of a `:not([open])` details element and some do, I guess? 

We'll see if can't fix it up thanks!
