### ISSUE TITLE
Add Experiment:  Send 103 Early Hint

### ISSUE THREAD

**Issue by scottjehl** [catchpoint/WebPageTest#2065]
LCP and render-blocking resources come to mind. Need to understand feasibility from our workers

https://www.fastly.com/blog/beyond-server-push-experimenting-with-the-103-early-hints-status-code

**Comment by rockeynebhwani** [comment]
@tkadlec - It will not be possible to achieve EarlyHints on some SaaS platforms at all so this opportunity will not be helpful for those platforms.

Also, I was chatting with Shopify team and it seems on Shopify for now they have limit of 2 Early Hints max. (they may change this in future). Also on Shopify, you can't add an early hints for 3rd party resource currently.
