### ISSUE TITLE
No font request in a waterfall for a page including several fonts

### ISSUE THREAD

**Issue by nhoizey** [catchpoint/WebPageTest#2109]
## Description

When running a test on a page that has a few fonts, WebPageTest's waterfall shows no font at all, while the same page's waterfall shows fonts in SpeedCurve's own WPT instance, and fonts are also visible in browsers devtools' network tab.

### Steps to reproduce

I can't share any public URL of the page unfortunately.

I ran test with desktop Chrome, from Paris, in my own Chrome browser, WPT and SpeedCurve.

### Expected result

Font requests should be visible in the waterfall.

### Actual result

There is no font request in WPT's waterfall.

Here are redacted screenshots from WPT and SpeedCurve:

![WebPageTest 2022-07-11](https://user-images.githubusercontent.com/78213/178298295-69bb10b2-354a-4aff-ab13-610af252de49.png)

![SpeedCurve 2022-07-11](https://user-images.githubusercontent.com/78213/178298336-f7c11eea-a978-4aaf-a419-94737210e2df.png)

### Related issues?

I don't think so.

**Comment by tkadlec** [comment]
That's my theory at the moment, @scottjehl. Need to double check the agents to see what fonts might already be loaded that might be tripping this up.

**Comment by nhoizey** [comment]
@scottjehl we discussed a little with Tim yesterday, the fonts are from the OpenSans family.

On this specific page, these are OpenSans Regular, SemiBold and Bold.
