### ISSUE TITLE
Allow for some if not all Custom Scripting to apply alongside experiments

### ISSUE THREAD

**Issue by scottjehl** [catchpoint/WebPageTest#2132]
Currently, experiment scripts run in place of any scripting that's applied to a test. Many scripting features should be compatible with experiments, while some (like multistep tests) may not. 

We should aim to preserve scripting in experiments.

**Comment by kevinfarrugia** [comment]
This ticket was closed but scripts are still not being copied onto experiments.

Example: https://www.webpagetest.org/video/compare.php?tests=220801_AiDcWC_539,220801_AiDc2D_537

```
navigate %url%/learn
```

Am I missing something?

**Comment by scottjehl** [comment]
Thanks @kevinfarrugia 

This was partly addressed but you're right that it's not fully fixed yet. We intend to keep what we can of scripts, but some settings will have to be overridden for the experiment itself (which also uses scripting).
