### ISSUE TITLE
Preloaded styles are loaded again by WPT

### ISSUE THREAD

**Issue by ebizindia** [catchpoint/WebPageTest#2166]
## Description
I have preloaded 3 CSS files but these are downloaded again by WPT. However, devtools show that these are not downloaded again.
Early Hints are enabled through htaccess-based preload and Cloudflare.
https://www.webpagetest.org/result/220718_BiDcZM_4H8/

### Steps to reproduce
Clear steps to reproduce the issue. If it's relevant and you're able, please provide a link to a WebPageTest run—it makes it _much_ easier for us to dig in.

### Expected result
I expect that the preloaded CSS files, which have also arrived before the 2nd download, should not have been downloaded again.

### Actual result
What actually happens?

### Related issues?
Any related issues filed already?

**Comment by tkadlec** [comment]
This one looks like a legitimate double download. It's looking like a Chrome issue and seems to be related to this: https://bugs.chromium.org/p/chromium/issues/detail?id=1345656

**Comment by ebizindia** [comment]
Funnily, this does not happen with a regular Chrome browse session (both
current and Canary).
