### ISSUE TITLE
Navigation issue on FireFox 

### ISSUE THREAD

**Issue by arvin-m** [catchpoint/WebPageTest#2196]
## Description
I noticed the Navigation issue that pops up in certain screen ration that blocks the current page. I am using the wide-screen monitor and only appears on Firefox

### Steps to reproduce
it was on all pages. Navigation / Hamburger bar is shown/active without any user interaction. start from: screen ration 1375*1162

### Expected result

The navigation list must be hidden
### Actual result
when you resize the browser window, the Hamburger bar list starts to show on the screen and blocks the page.

### Related issues?
![fire-fox-issue](https://user-images.githubusercontent.com/54293267/181590669-09ad568b-ac45-4e76-9c20-dbad5cfea43c.PNG)

**Comment by deathbearbrown** [comment]
Ooo, a fun bug. Here's a screen recording of the behavior I am seeing on firefox. I will look into issues with media queries and transforms in firefox.

https://user-images.githubusercontent.com/607541/183719350-3906503e-2b10-422f-a659-f8728a7d86cd.mov


@arvin-m do you see this weird animation flash or does the navigation stay on screen for you?

**Comment by deathbearbrown** [comment]
A related issue! #2062

**Comment by arvin-m** [comment]
The navigation stay on screen
