### ISSUE TITLE
`<script type="module">` should satisfy Defer Render-Blocking Scripts warning

### ISSUE THREAD

**Issue by zachleat** [catchpoint/WebPageTest#2214]
https://www.webpagetest.org/result/220801_AiDcC5_EP3/3/experiments/#Quick

![image](https://user-images.githubusercontent.com/39355/182231301-f3f39faf-a05c-4f11-8059-b4a779c097de.png)

Both of these scripts are `type="module"`, which imply `defer` https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script#attr-type

**Comment by zachleat** [comment]
(also, hello friends 👋🏻)

**Comment by scottjehl** [comment]
Hey Zach! Thanks. Is it possible this test was run in a non-chrome browser? We're working on our render blocking check for browsers that don't pass it to us directly and it'd be useful to know. We may have a fix shortly :)

**Comment by tkadlec** [comment]
Heya Zach!

@scottjehl Looks like it's Chrome, which means Chrome may have a bug in their render blocking reporting here.

**Comment by scottjehl** [comment]
oh... the test result is RIGHT THERE. Thanks, friend. Grabbing coffee now don't mind me
