### ISSUE TITLE
Paying customer that runs out of credits are unable to use webpagetest?

### ISSUE THREAD

**Issue by LarsBuur** [catchpoint/WebPageTest#2240]
I Love webpagetest. Please make the account / payment part better. 

![CleanShot 2022-08-04 at 07 48 03](https://user-images.githubusercontent.com/3585707/182772308-13ba0d6b-546c-49f8-9c97-db1bfa11f2d5.png)

Guess what happens when I click Upgrade. I am sent to  /account where I have to contact support?? - no way to just buy more credits.

Now support uses another auth system so even though I am logged in to webpagetest then I am not logged in to support system.?

Finally given I am a small paying customer of webpagetest I get a lessor experience than non paying customers and are not able to use it after my credits run out. I have to logout of webpagetest before I can run new tests.

**Comment by tkadlec** [comment]
Hey @LarsBuur!

> Guess what happens when I click Upgrade. I am sent to /account where I have to contact support?? - no way to just buy more credits.

Yeah, this stinks and it's going to get fixed _very_ soon. I'll keep you posted.

> Now support uses another auth system so even though I am logged in to webpagetest then I am not logged in to support system.?

Hmm...will look into this so we can tidy that up. Thanks for the heads up!

**Comment by LarsBuur** [comment]
Hi @tkadlec 

Thank you for your reply. I think you should also look into the issue where I am unable to use webpagetest before I log out.
