### ISSUE TITLE
Experiments (and control run) do not correctly highlight JavaScript execution

### ISSUE THREAD

**Issue by kevinfarrugia** [catchpoint/WebPageTest#2321]
## Description
WPT highlights JavaScript execution in pink. When running an experiment on a page which is dependent on JavaScript, not all JavaScript files show the pink bar as would be expected.

### Steps to reproduce
- Run a test for m.youtube.com (https://www.webpagetest.org/result/220906_BiDcV2_92A/1/details/#waterfall_view_step1)
- See the pink bars in the waterfall chart.

![Screenshot from 2022-09-06 15-11-54](https://user-images.githubusercontent.com/8075326/188644769-cf39dcc6-a2fd-45af-a749-0a73b5f46e80.png)

- Run an experiment, any experiment will do. In the example, I block requests to https://example.com (https://www.webpagetest.org/result/220906_BiDc2M_937/)
- Open the waterfall charts and notice that the pink bars are no longer present.

![Screenshot from 2022-09-06 15-14-14](https://user-images.githubusercontent.com/8075326/188644724-6a35a094-898c-402f-8d8e-fdd4722f9ebf.png)

### Expected result
- JavaScript execution happens on the experiment and control runs and therefore should be visible on the waterfall chart.

### Actual result
- JavaScript execution pink bars aren't present.

**Comment by scottjehl** [comment]
Thanks @kevinfarrugia 

That's an odd one! We'll take a look.
