### ISSUE TITLE
Lighthouse Page Redesign Remaining Items

### ISSUE THREAD

**Issue by scottjehl** [catchpoint/WebPageTest#2555]
The revamp of our lighthouse results pages is coming along. I wanted to document what's done and what's left to do here as I pass it off to someone who thinks in PHP :)

PR here https://github.com/WPO-Foundation/webpagetest/pull/2513

Current visual screenshot:
<img width="993" alt="image" src="https://user-images.githubusercontent.com/214783/204601963-89a01abe-9a5e-4b75-bf0a-19b5529e9992.png">

This template is built using our lighthouse.php page using the lighthouse JSON. It uses our new template setup but I did not go as far as templating the markup itself in Blade yet (more on that below). The test result navigation for this PR is tweaked to treat LH like other result pages instead of an external one. If the lighthouse run is the ONLY test type (if you choose lighthouse from the start test page), no other result pages will be offered in the results nav.

## Still to do:

- [x] The details for each opportunity/audit are not currently being written to HTML dynamically. I did make a couple static HTML examples that are being outputted in each opportunity right now that can be used as a model for how the details should output in either a table or list depending on type.
- [x] the links to sort opportunities by metric are stubbed and not at all wired into actual functionality. I was thinking a server-side sort for these would be easiest though?
- [x] tree map link doesn't go anywhere. do we have tree maps enabled?? how do we if not?
- [x] Style diagnostics and opportunities uniquely somehow

- [x] we need a great screenshot view for the social media preview of these results. 
- [x] The svg meter values in the page are not currently calculated to show the 0/360 dial percent, so that needs to be set in each svg. Their colors are correct however.
- [x] Figure out a call to action up top for lighthouse-only results to run a fuller webpagetest run to get more info than lighthouse provides
- [x] Somehow mention that PRO experiments can be run to improve lighthouse scores
- [x] CSS for smallscreen layouts needs fixing up

 - [x] write some php classes to parse the json and provide some helper methods for templating this page properly. 
- [x] We're not including a LH filmstrip or screenshot. The current screenshot is from a broader WPT result so if it's a lighthouse-only run, there's no screenshot currently. We should consider enabling the filmstrip and a screenshot to use at the top of the page. I'd consider the filmstrip to be lower priority for launch if it's tricky.
- [x] The page title and social media description should read something about "WebPageTest Lighthouse Result for xyz.com"

**Comment by stoyan** [comment]
- [ ] Make "Show audits relevant to metrics:" links work
- [ ] We have hardcoded Diagnostics, Passed Audits and Opportunities categories, but they are different in different sections (e.g. Accessibility is different than Perf)
- [ ] Figure out how to match LH report when listing items in a category, e.g. hide items such as "Network Requests" and "Final Screenshot" from Diagnostics

**Comment by stoyan** [comment]
- [ ] sort "Opportunities" by potential ms wins

**Comment by scottjehl** [comment]
Details are filled in for most now! 

Some notes as I look at it...

Tree map link: keep? Make work if so
<img width="322" alt="image" src="https://user-images.githubusercontent.com/214783/206585851-cfa6f309-d393-4777-8fe6-51e7bf88d099.png">

PWA opportunities have details that are not table/opps/chains. Debuginfo I think... Needs to be handed in partial
<img width="754" alt="image" src="https://user-images.githubusercontent.com/214783/206586010-0d2b2bdc-6952-48f7-9c0f-35a820f5d5d2.png">


Accessibility details doesn't seem to use the same keys and table structure as other

<img width="766" alt="image" src="https://user-images.githubusercontent.com/214783/206586143-9f49d724-5785-4a6a-b70c-3e780f77a1c6.png">


LCP details aren't populated 
<img width="800" alt="image" src="https://user-images.githubusercontent.com/214783/206586244-2779aae1-bb46-41bd-bcda-18826b6da318.png">

**Comment by scottjehl** [comment]
Also, opportunities sections need some additional info added on the list items and such:
<img width="859" alt="image" src="https://user-images.githubusercontent.com/214783/206586427-50ababcb-0649-4dd9-aa9a-0c9052a0d5cc.png">
Estimated savings etc

**Comment by scottjehl** [comment]
Lastly, we should surface links to relevant experiments in a few key places for v1.

**Comment by scottjehl** [comment]
also add https://github.com/WPO-Foundation/webpagetest/issues/2576
and https://github.com/WPO-Foundation/webpagetest/issues/2575

to this release

**Comment by scottjehl** [comment]
Still to do:

- [ ] Sort opps by potential wins?
- [ ] Fix the closing divs somewhere so the footer is no longer inside the content wrapper
- [ ] Anywhere to link to relevant experiments easily??
- [ ] Test against the default LH view to see if we differ in scoring at all (pass average fail particularly)

**Comment by scottjehl** [comment]
Add bottom padding to layout

**Comment by stoyan** [comment]
- [ ] grey manual icons
- [ ] truncate data uris
- [ ] empty detail tables
