### ISSUE TITLE
"View:" menu partially unusable on Web Vitals page with a mouse

### ISSUE THREAD

**Issue by josebolos** [catchpoint/WebPageTest#2976]
## Description

The "View:" menu in the Web Vitals page is partially occluded by the "(Collected in this WPT test run)" heading in the Web Vitals page. For some reason, this heading element, which has a CSS selector of `#result > h3:nth-child(1) > em:nth-child(1)`, has a `z-index: 10`, which seems to cause the heading to display in front of the "View:" menu.

This makes it hard or impossible to reach the last 7 elements of the "View:" menu with the mouse pointer.

### Steps to reproduce

1. Create any test
2. After the test is finished, go to the "Web Vitals" page for that test, e.g. `https://www.webpagetest.org/vitals.php?test=ABCD`
3. Click on the "View:" menu, move the mouse pointer down the recently opened menu so it reaches the "Domains" item or lower.

### Expected result

Menu opens and I'm able to interact with all the elements in the menu.

### Actual result

I'm not able to select with the mouse any items below "Domains", as the menu closes when the mouse reaches the "(Collected in this WPT test run)" heading.

### Related issues?

None that I could find.

Screenshot:
<img width="1268" alt="Screenshot of the WPT Web Vitals page, showing the View menu open, with a heading displaying on top" src="https://github.com/catchpoint/WebPageTest/assets/1792637/6d82eb4a-9a95-42bb-bc31-f0d2f5dcad07">

**Comment by mjkozicki** [comment]
@josebolos Thank you for submitting the issue. It has been resolved.
