### ISSUE TITLE
Add WebPageTest identifier to CO2.js green hosting check

### ISSUE THREAD

**Issue by fershad** [catchpoint/WebPageTest#3041]
## Feature Request Summary
CO2.js v0.14.2 adds a User-Agent string header to green hosting checks that are performed.

By default this header sends the current version of CO2.js being used. There is an option of developers to add the name of their app/project to the User-Agent string. 

### What's the motivation or use case for the change/feature?
This gives the Green Web Foundation some more visibility of who's using our open source tools.

Docs: https://developers.thegreenwebfoundation.org/co2js/tutorials/check-hosting/#check-one-domain-for-green-hosting

Happy to create a small PR for this.

**Comment by lbartoli79** [comment]
We will try to take care of this in the following release

**Comment by mjkozicki** [comment]
Completed.
