### ISSUE TITLE
Add ability to specify min/start time for custom waterfalls

### ISSUE THREAD

**Issue by jspurlin** [catchpoint/WebPageTest#3042]
## Feature Request Summary
This is a request to add the ability to set a min/start time for custom waterfalls. Today you can specify a max/end time, but no start time.

### What's the motivation or use case for the change/feature?
I want the ability to "zoom in" on a specific chunk of time from the waterfall, say 2-3.5s for example. Today I can only see 0-3.5s

**Comment by slightlyoff** [comment]
This is a request coming from MSFT's use of WPT internally. I don't have edit permissions on the bug, but if the owners here feel like it would be best for us to contribute patches in support of this, let us know.

/cc @pmeenan @andydavies

**Comment by pmeenan** [comment]
FWIW, I'm happy to review PR's or answer any questions (or finally take a crack at it myself) but I don't have repository permissions to merge so that part would depend on Catchpoint.
