### ISSUE TITLE
Reset password on webpagetest 500 error page 

### ISSUE THREAD

**Issue by 25prathamesh** [catchpoint/WebPageTest#3043]
I encountered an issue when trying to reset my password via a link sent to my email. After entering a new password and submitting it, I received a 500 error page. However, I can still log in using the username and password I set during the process; only the success page displays the 500 error.

<img width="897" alt="Screenshot 2024-02-09 at 3 11 40 PM" src="https://github.com/catchpoint/WebPageTest/assets/10120153/0c1b3749-6c7a-44ca-8bea-93f9753de45c">

**Comment by mjkozicki** [comment]
Closed as not reproducible,
