### ISSUE TITLE
WPT click or clickAndWait commands are synthetic and do not dispatch trusted events.

### ISSUE THREAD

**Issue by MaryamHuntsperger** [catchpoint/WebPageTest#3048]
## Description
WPT action APIs are synthetic and do not dispatch trusted events. This means that events triggered by click or clickAndWait will be ignored by the EventTiming APIs
### Steps to reproduce
Create an event handler that listens to click event and logs "isTrusted" property of the event with a command like:
execAndWait document.body.addEventListener("click", function(e){console.warn('isTrusted is ', e.isTrusted)}, {passive: true, capture: true})
Then run a clickAndWait command like:
clickAndWait  id=<>

This will log onto the console that "isTrusted is false"

### Expected result
We want that click event's isTrusted property to be true.

**Comment by jspurlin** [comment]
FYI @slightlyoff. Currently the [EventTiming API ignores events where isTrusted is false](https://w3c.github.io/event-timing/#sec-performance-event-timing:~:text=If%20event%E2%80%99s%20isTrusted%20attribute%20value%20is%20set%20to%20false%2C%20return%20false.) which means we can't utilize the signals from that API in WPT. I believe MSFT's internal WPT usage is interested in picking this up soon

**Comment by jspurlin** [comment]
It'd be interesting to generalize this item to include also being able to dispatch other trusted events (like touch and keyboard events)

**Comment by mjkozicki** [comment]
This is an agent enhancement, referenced above.
