### ISSUE TITLE
WebPageTest API wrapper not contains possibility to add api key as a header to command-line tool

### ISSUE THREAD

**Issue by malgorzataxkowal** [catchpoint/WebPageTest#3054]
## Description
I used  to use command line tool to connect with webpagetest and execute scripts on the site. I used to provide the api key via the "-k" parameter. in the latest version of webpagetest the key parameter has been deprecated and addition of api key is possible via the request header. The documentation for command line tool hasn't been updated yet.  There is no possiblity to run webpagetest command with header options.  Of course, there is the option to send a request with the header using the curl command but it gets complicated when I want yo run/test srcipts rather than a single url.

### Steps to reproduce
1. install webpagetest command line ([https://www.npmjs.com/package/webpagetest](https://www.npmjs.com/package/webpagetest))
2. from terminal run command: webpagetest test https://docs.webpagetest.org/api/integrations/ --key {YOUR_API_KEY}

### Expected result
If the key parameter is deprecated in command line tool and only header is accepted as the api key, the webpagetest command should have option to add header to the command. 

### Actual result
It is not possible to use the webpagetest command line tool as there is no option to add a header to the command.

**Comment by claud-io** [comment]
Hello @malgorzataxkowal can you please try to update the API wrapper to latest version? it should fix your issue. thanks.

**Comment by claud-io** [comment]
@malgorzataxkowal closing this since issue is resolved, lmk if anything, thanks
