### ISSUE TITLE
WPT GitHub Action failed with error: An error occurred processing your request (missing API key).

### ISSUE THREAD

**Issue by l1lYa** [catchpoint/WebPageTest#3061]
## Description
Of course, we have a subscription and an active API Key. We use GitHub WPT Action to test our sites. It looks like with your security update "Security update: API keys are now required in the X-WPT-API-KEY header. The query parameter k= will be ignored. Current API keys will continue to work." something broke with GitHub Actions integration. Can you tell us what needs to be done to make everything work again?

### Steps to reproduce
Set up the API key in the repository secrets > Try to use GH Action WPT Integration.

### Expected result
The action is being launched. The WPT test runs and shows the result.

### Actual result
GitHub Action failed with error: An error occurred processing your request (missing API key).

**Comment by claud-io** [comment]
@l1lYa a fix will be deployed shortly, thanks for the feedback.

**Comment by claud-io** [comment]
@l1lYa issue should be fixed. Please let me know if anything, thanks

**Comment by claud-io** [comment]
@l1lYa  closing this issue, since is resolved, lmk if anything.
