### ISSUE TITLE
Visual Comparison Test doesn't work

### ISSUE THREAD

**Issue by SilencerWeb** [catchpoint/WebPageTest#3064]
## Description
I'm trying to use a Visual Comparison Test. But once I fill in links and click on the button "Start Test", I get redirected to a blank page

I have tried disabling AdBlock for the website but it didn't help. I have also tried to check if it will work in the Incognito mode without any cookies, local storage and extensions but it didn't help either

Console and Network tabs in the DevTools don't show any errors

### Steps to reproduce
1. Navigate to https://www.webpagetest.org/video/
2. Fill in "Reddit" and "https://reddit.com/" as first item
3. Fill in "YouTube" and "https://www.youtube.com/" as second item
4. Click on the button "Start Test"

Video:

https://github.com/catchpoint/WebPageTest/assets/20713191/1c38d094-2e66-405c-b7f5-adb089f20a5f

### Expected result
I see a Visual Comparison Test in progress, then I see the result of the Visual Comparison Test

### Actual result
I see a blank page

### Related issues?
I haven't found any

**Comment by claud-io** [comment]
Hello @SilencerWeb , issue has been fixed, let me know if anything, thanks

**Comment by claud-io** [comment]
closing since issue is fixed and seems working fine.
