### ISSUE TITLE
Private Instance has per-IP monthly test limit enforced

### ISSUE THREAD

**Issue by thedoc31** [catchpoint/WebPageTest#3103]
## Description
When running WPT private instances, a monthly IP-based rate limit is still enforced when testing via UI. This makes sense for a publicly-exposed tool, but does not make sense for a private instance scenario where we want our users to have unlimited access to use WPT for testing where users will all share the same egress IP.

There is no documentation on how to turn this off or how to redirect the WPT UI login mechanism to accept SSO/SAML logins or preauthenticated sessions to bypass the restriction.

It appears that this should be configurable based on the `rate_limit_anon` and `rate_limit_anon_monthly` settings, but it's not documented in which settings file these should go.

I tried placing these settings in the `locations.ini` file but that doesn't seem to do the trick.

```
[us-west-2-linux-group]
1=us-west-2-linux
label="US West 2 - Linux (Oregon)"
lat=45.777102
lng=-119.788742
rate_limit_anon=0
rate_limit_anon_monthly=1000000
default=us-west-2-linux

[us-west-2-linux]
browser=Chrome,Chrome Beta,Chrome Canary,Firefox,Firefox Nightly,Opera,Opera Beta,Opera Developer
label="US West 2 - Linux (Oregon)"
region=us-west-2
rate_limit_anon=0
rate_limit_anon_monthly=1000000
```
![image](https://github.com/user-attachments/assets/a7079053-e83f-46d6-885f-4e92c6c8a02e)

### Steps to reproduce
Set up private instance WPT server and client
DO NOT LOG IN
Issue more than 50 performance test requests from the same IP
See "Oops! You've reached the limit for this month" error message

### Expected result
For private instance WPT, monthly anonymous IP-based rate limit should not be enforced

### Actual result
Monthly anonymous IP-based rate limit is enforced

### Related issues?
None as far as I can tell

**Comment by Dgeorgiev90** [comment]
Settings those in the settings.ini did the trick for us:

rate_limit_anon_monthly=100000000
rate_limit_anon=100000000

**Comment by mjkozicki** [comment]
@Dgeorgiev90 solution will work. Closing.
